excerpt_separator: <!-- more -->
url: http://bywatchingyou.com
name: "By Watching You - Webcomic"
description: "The epic web comic you've been waiting for. A breeding ground for tranks, lo-bos, and zipheads."
markdown: kramdown
azntag: "dankuck-20"
google_tracking_id: "UA-52383063-1"
